export const mocTagsData = {
  items: [
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 17,
      name: 'zyte',
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 70,
      name: 'zypper',
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 19,
      name: 'zynq-ultrascale+',
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 2,
      name: 'zynqmp',
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 275,
      name: 'zynq',
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 18,
      name: 'zxspectrum',
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 2,
      name: 'zxingobjc',
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 30,
      name: 'zxing-js',
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 16,
      name: 'zxing.net.mobile',
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 153,
      name: 'zxing.net',
    },
  ],
  has_more: false,
  page: 1,
  page_size: 10,
  total: 65785,
};
